velib_project_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGIS_VELIB_HOST') }}"
      user: "{{ env_var('POSTGIS_VELIB_USER') }}"
      password: "{{ env_var('POSTGIS_VELIB_PASSWORD') }}"
      port: "{{ env_var('POSTGIS_VELIB_PORT') | int }}"
      dbname: "{{ env_var('POSTGIS_VELIB_DB') }}"
      schema: public               # DBT utilisera ce schéma par défaut
      threads: 1
      keepalives_idle: 0