services:
  shiny:
    build:
      context: ./shiny
      dockerfile: Dockerfile
    container_name: shiny-velib
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./shiny/app:/srv/shiny-server/app
    ports:
      - "3838:3838"
    networks:
      - idfm_network

networks:
  idfm_network:
    external: true